### ISSUE TITLE
Ver 5.3.1 & Ver 5.3.2 crash in WIN 10 64 bit if run as administrator (properties -> compatibility).  No problem in Ver 5.2.1 as administrator or not.

### ISSUE THREAD

**Issue by gomactrading** [OrangeDrangon/android-messages-desktop#371] opened 2022-04-08 02:46 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by OrangeDrangon** [comment] 2022-04-08 03:32
I cannot reproduce this. Without more details in the next few days, I will be closing this.

**Closed** 2022-04-23 19:04 UTC
Labels: bug
