### ISSUE TITLE
Google Fi Integration

### ISSUE THREAD

**Issue by jrhardman64** [OrangeDrangon/android-messages-desktop#157] opened 2020-11-07 20:31 UTC
Issue:
Google Fi was recently integrated into Android Messages instead of using Hangouts as the default messaging app.  The Messages app provides a link to sign in with your email address, but then I get an error that I am not using a supported browser.  I can use the old way of signing in with the QR code, but then I lose the extra features that I would get with using my Google Fi account.

Solution:
Enable signing in with my Google Fi account.  Not sure what it would take to become a "supported browser" within the app?

Alternatives:
None that I can think of.

Screenshot:
![image](https://user-images.githubusercontent.com/36314071/98450835-1b86a600-210e-11eb-973c-e4c879abbe76.png)
![image](https://user-images.githubusercontent.com/36314071/98450846-33f6c080-210e-11eb-9d41-a0a40d3c1425.png)
![image](https://user-images.githubusercontent.com/36314071/98450856-48d35400-210e-11eb-90c5-10675ba188ec.png)

**Comment by OrangeDrangon** [comment] 2020-11-08 06:39
Hello @jrhardman64 

I would love to support this but ultimately I have no feasible way to. I do not have Google Fi. It also may either prove to be extremely easy to implement or impossible depending on how those integrations are implemented in the website.

If you or anyone else would like to give it a go I would be happy to merge it and answer any questions about the horrible code base.

Sorry about any trouble this causes you. Until this is merged I recommend giving up some of those features or using it in a normal browser.

**Comment by ofek** [comment] 2020-12-03 16:12
@OrangeDrangon Would you be willing to accept payment to look into/implement this?

**Comment by innesst** [comment] 2020-12-03 16:36
Can you log in successfully here? Nothing that this app can do will work if you can't log in with a regular browser.
messages.google.com/web

**Comment by ofek** [comment] 2020-12-03 16:49
I don't have Fi yet to try this. I can't physically use a phone and have been using the Hangouts extension, but since Google is removing calls in January I'm looking for another way to call and text from my computer in a separate window.

**Comment by jrhardman64** [comment] 2020-12-03 16:59
Yes, I can log in that way.  What I have done is install the progressive
web app that Google lets you install through chrome.  It has the same issue
with not showing a notification number in the taskbar on Windows, but it
does work with Google Fi.

**Comment by ofek** [comment] 2020-12-03 17:22
@jrhardman64 What progressive web app?

**Comment by jrhardman64** [comment] 2020-12-03 17:28
Go to messages.google.com and it will give you the option to download the
app under Chrome settings.  Mine shows "Open in Messages" since I've
already downloaded it.

[image: image.png]

**Comment by ofek** [comment] 2020-12-03 17:34
Ah I understand, thanks! I wonder why it does not work in this Electron app.

**Comment by ofek** [comment] 2020-12-03 18:55
@jrhardman64 Hey if you don't mind, I have 2 quick questions about the PWA before I buy a phone, Fi, etc.

1. Can you also receive calls? If so, no notification right?
2. What does it look like when sized down? I've had Hangouts in a corner like this for years (I cut off numbers for picture):

![Capture](https://user-images.githubusercontent.com/9677399/101074733-1a129700-356f-11eb-9cf5-37640244f3ab.PNG)

**Comment by jrhardman64** [comment] 2020-12-03 19:03
1. Yes you can make and receive calls from this app.  You will get a pop-up
notification when you are receiving a call that you can answer on your PC
and then talk through your mic that is connected.
2. See below:

[image: image.png]

**Comment by ofek** [comment] 2020-12-03 19:16
Awesome, thanks! The image isn't coming through though.

**Comment by jrhardman64** [comment] 2020-12-03 19:22
Here's an attachment.  See if that works better.

**Comment by ofek** [comment] 2020-12-03 21:15
@jrhardman64 Nothing came through but thank you for trying! Does it resize in a similar way?

**Comment by jrhardman64** [comment] 2020-12-03 23:54
Yes it does!

**Comment by ofek** [comment] 2020-12-04 00:06
Fantastic, thanks!!! I'll buy a phone then

**Comment by OrangeDrangon** [comment] 2020-12-04 04:41
Can I consider this closed?

**Comment by crimsonknave** [comment] 2020-12-09 16:28
@OrangeDrangon I'm a Google FI user and would be happy to try and debug this. From a bit of searching it seems that there is some setting that is/isn't set in electron that should fix this. I've seen suggestions that it's caused by development version or some other settings. Is there any documentation on how to build/run it locally? If I can run it locally I'll give it a shot to see if I can find something that fixes the issue.

**Comment by OrangeDrangon** [comment] 2020-12-10 00:53
The code is pretty ugly but feel free to take a look.

Steps to contribute:
Fork
Clone
Edit
`yarn start` to build and run assuming you have electron installed.

**Comment by airbreather** [comment] 2020-12-11 15:13
This seems to be the same issue as timche/gmail-desktop#174.

That project fixes it by grabbing the latest user agent string from https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox and advertising that to the web service, on an opt-in basis.

**Comment by numbernegative** [comment] 2020-12-14 18:56
The YTM Desktop player that's come to replace since GPM shut down had this issue as well: https://github.com/ytmdesktop/ytmdesktop/issues/67
Their solution was to use the Firefox User Agent rather than Chromium
https://github.com/ytmdesktop/ytmdesktop/pull/72
They said it's a temporary fix when this merge was made but it's still working to this day so maybe it'll work for our purposes too?

**Comment by OrangeDrangon** [comment] 2020-12-14 20:54
Interesting google products working better with a firefox user agent. What a world we live in?

Thanks
Kyle

________________________________

**Comment by OrangeDrangon** [comment] 2020-12-15 21:52
I can open a branch where the user agent is set to firefox with a link to some downloads if anyone is interested in giving it a try.

**Comment by numbernegative** [comment] 2020-12-16 16:13
Worth a shot. I've got FI so I can test it.

**Comment by numbernegative** [comment] 2020-12-16 23:57
Tested with that pull and it didn't work. However I took a closer look at the YTMDesktop app and more or less copied their version of how they did it and it allowed me to log in and the Fi side seems functional.
```
    // set user agent to potentially make google fi work
	
	mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
        {
            urls: ['https://accounts.google.com/*'],
        },
        (details, callback) => {
            const newRequestHeaders = Object.assign(
                {},
                details.requestHeaders || {},
                {
                    'User-Agent':
                        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0',
                }
            )
            callback({ requestHeaders: newRequestHeaders })
        }
    )
```
![image](https://user-images.githubusercontent.com/11063321/102420536-f36d4b00-3fc7-11eb-92a8-9a58104ce3f6.png)
Texts are synced as they should as well as being able to dial out. Echo test confirmed it's picking up the mic set with the settings in top right corner.

**Closed** 2020-12-19 02:29 UTC
Labels: enhancement, help wanted

**Comment by briantho** [comment] 2022-09-13 21:26
this seems broken again. can you please fix it? I can't sign into messages from google fi. Here is a screenshot

![image](https://user-images.githubusercontent.com/3977205/190012162-9d357325-6b54-460c-bb19-996e62e6857f.png)

**Comment by OrangeDrangon** [comment] 2022-09-14 21:21
In the future feel free to open a new issue instead of reviving a closed one it makes it much easier to track :)
